### PR TITLE
add EXT-X-ALLOW-CACHE tag

### PR DESCRIPTION
**Pull request by HiroyukTamura**
### feature
- default value of allowCache() is **true**
- **must** write EXT-X-ALLOW-CACHE tag with YES or NO

please review and rewrite

### CODE REVIEW

**Comment by HiroyukTamura** [comment]
oops, sorry please fix typo `builder.allowChache` ->`builder.allowCache`

**Comment by carlanton** [comment]
Thank you for your pull request :) Unfortunately it does not compile. Maybe you can fix this? Some tests would also be good!

EXT-X-ALLOW-CACHE is deprecated and no longer part of the HLS-spec. I'd prefer if you can make the flag optional (eg. `Optional<Boolean> allowCache()`) so we don't add it to all playlists by default.

Cheers,
Anton

**Comment by HiroyukTamura** [comment]
ok, all fix and make it optional

**Comment by carlanton** [comment]
Thanks!

**Pull request merged**
